/// @description Insert description here
// You can write your code in this editor
texty -= scroll_speed;
draw_set_font(aboutFont);
draw_text_ext(textx, texty,"WHEN THE HUMAN RACE BECAME FAR TOO GREEDY WITH A SEARCH TO DISCOVER A NEW HABITABLE PLANET, THEY BEGAN TO SPRED A DEADLY VIRUS ACROSS MANY DIFFERENT POPULATIONS IN THE SUROUNDING GALAXY, INCLUDING YOURS. IN AN ATTEMPT TO ELIMINATE THE VIRUS, YOUR SPECIES DECIDES TO DEAL WITH THE PROBLEM AT ITS SOURCE", line_height, room_width - 200);